cmake ^
	-H. ^
	-B"%BUILD_DIR%" ^
	-G "Visual Studio 15 2017 Win64" ^
	-DCMAKE_BUILD_TYPE=%BUILD_TYPE% ^
	-DBOOST_ROOT="%BOOST_ROOT%" ^
	-DOPENSSL_ROOT_DIR="%OPENSSL_ROOT%" ^
	-DZLIB_ROOT="%ZLIB_ROOT%" ^
	-DUSE_STREAMLABS_RESOURCE=ON

cmake --build "%BUILD_DIR%"