cmake ^
	-H. ^
	-B"%BUILD_DIR%" ^
	-G "Ninja" ^
	-DCMAKE_BUILD_TYPE=%BUILD_TYPE% ^
	-DBOOST_ROOT="%BOOST_ROOT%" ^
	-DBoost_COMPILER="-vc141" ^
	-DOPENSSL_ROOT_DIR="%OPENSSL_ROOT%" ^
	-DZLIB_ROOT="%ZLIB_ROOT%" ^
	-DWIN_MT="%WIN_MT%" ^
	-DUSE_STREAMLABS_RESOURCE=ON

cmake --build "%BUILD_DIR%"