mkdir "%DEPS_LOCAL_PATH%"
curl -kLO "%DEPS_DIST_URI%/%ZLIB_DIST_NAME%.7z" -f --retry 5
curl -kLO "%DEPS_DIST_URI%/%OPENSSL_DIST_NAME%.7z" -f --retry 5
curl -kLO "%DEPS_DIST_URI%/%BOOST_DIST_NAME%.7z" -f --retry 5
7z x "%ZLIB_DIST_NAME%.7z" -o"%DEPS_LOCAL_PATH%\%ZLIB_DIST_NAME%" -y
7z x "%OPENSSL_DIST_NAME%.7z" -o"%DEPS_LOCAL_PATH%\$(OPENSSL_DIST_NAME)" -y
7z x "%BOOST_DIST_NAME%.7z" -o"%DEPS_LOCAL_PATH%\%BOOST_DIST_NAME%" -y